---
- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: false

- name: Setup VM
  when: "vm_name not in existing_vms.list_vms"
  block:
    - name: Upload VM disk to the server
      ansible.builtin.copy:
        src: /home/itrooz/tmp/cirros-0.6.3-x86_64-disk.img
        dest: /var/lib/libvirt/images/cirros.img
        mode: '0644'

    - name: Define vm
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'vm-template.xml.j2') }}"

    - name: Start VM
      community.libvirt.virt:
        command: start
        name: "{{ vm_name }}"
